version: "3.5"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - 27017:27017
    command: mongod